name: challenge

on: [push]

jobs:
    job1:
        name: JOB1-ubuntu
        runs-on: ubuntu-latest
        steps:
        - name: Step 1
          uses: actions/checkout@v2
        - name: Step 2
          run: date
    job2:
        name: JOB2-windows
        runs-on: windows-latest
        steps:
        - name: Step 1
          uses: actions/checkout@v2
        - name: Step 2  
          run: date
    job3:
        name: JOB3-macos
        runs-on: macos-latest
        steps:
        - name: Step 1
          uses: actions/checkout@v2
        - name: Step 2  
          run: date
    job4:
        name: JOB4-ubuntu
        runs-on: ubuntu-latest
        needs: [job1, job2, job3]
        steps:
        - name: Step 1
          uses: actions/checkout@v2
        - name: Step 2
          run: |
               echo "All jobs completed successfully"
               date
