name: challenge

on: [push]

jobs:
    job1:
        name: JOB1-ubuntu
        runs-on: ubuntu-latest
        steps:
        - name: Step 1
          uses: actions/checkout@v2
        - name: Step 2
          run: date
    JOB2-windows:
        runs-on: windows-latest
        steps:
        - name: Step 1
          uses: actions/checkout@v2
        - name: Step 2  
          run: date
    JOB3_macos:
        runs-on: macos-latest
        steps:
        - name: Step 1
          uses: actions/checkout@v2
        - name: Step 2  
          run: date
    JOB4_ubuntu:
        runs-on: ubuntu-latest
        needs: [job1, JOB2-windows, JOB3_macos]
        steps:
        - name: Step 1
          uses: actions/checkout@v2
        - name: Step 2
          run: |
               echo "All jobs completed successfully"
               date
